package com.newer.blog.data.dao;

import com.newer.blog.data.entity.TblBlog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface IBlogDAO {
   //分页
    //总数
    public int getTotalCount();
    public List<TblBlog> selectByPage(Map<String,Object> param);
    //新增
    public void insertBlog(TblBlog blog);
    //查询全部
    public List<TblBlog> selectAll();

    int deleteByPrimaryKey(Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BLOG
     *
     * @mbggenerated Mon Aug 17 11:05:19 CST 2020
     */
    int insert(TblBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BLOG
     *
     * @mbggenerated Mon Aug 17 11:05:19 CST 2020
     */
    int insertSelective(TblBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BLOG
     *
     * @mbggenerated Mon Aug 17 11:05:19 CST 2020
     */
    TblBlog selectByPrimaryKey(Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BLOG
     *
     * @mbggenerated Mon Aug 17 11:05:19 CST 2020
     */
    int updateByPrimaryKeySelective(TblBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_BLOG
     *
     * @mbggenerated Mon Aug 17 11:05:19 CST 2020
     */
    int updateByPrimaryKey(TblBlog record);
}